default[:php_build] = {
  :prefix       => "/usr/local",
  :repository   => "https://github.com/CHH/php-build",
  :git_action   => "sync",
  :git_revision => "master",
  :config_dir   => "/usr/local/share/php-build",
  :configure    => [
    { "with_apxs2"      => "/usr/sbin/apxs" },
    { "with_jpeg_dir"   => "/usr" },
    { "with_png_dir"    => "/usr" },
    { "with_curl"       => "/usr" },
    { "with_mcrypt"     => "/usr" },
    { "with_zlib_dir"   => "/usr" },
    { "with_mysql"      => "mysqlnd" },
    { "with_mysqli"     => "mysqlnd" },
    { "with_pdo_mysql"  => "mysqlnd" },
    "with_gettext",
    "with_gd",
    "with_kerberos",
    "with_opnssl",
    "with_pear",
    "with_tidy",
    "with_pdo_sqlite",
    "with_readline",
    "with_xmlrpc",
    "with_xsl",
    "with_zlib",
    "enable_bcmath",
    "enable_cgi",
    "enable_exif",
    "enable_fpm",
    "enable_ftp",
    "enable_mbstring",
    "enable_pcntl",
    "enable_shmop",
    "enable_soap",
    "enable_sockets",
    "enable_sysvsem",
    "enable_sysvshm",
    "enable_xmlreader",
    "enable_zend_signals",
    "enable_zip",
    "disable_debug",
  ],
}
